apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"mongo"},"name":"mongo","namespace":"default"},"spec":{"clusterIP":"None","ports":[{"port":27017,"targetPort":27017}],"selector":{"role":"mongo"}}}
  creationTimestamp: 2019-02-09T22:53:03Z
  labels:
    name: mongo
  name: mongo
  namespace: default
  resourceVersion: "45376598"
  selfLink: /api/v1/namespaces/default/services/mongo
  uid: 3583d2f4-e929-11e8-a267-42010a80013a
spec:
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    role: mongo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
