apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: website-server
  name: website-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: website-server
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - --
        - npm run forever-start
        env:
        - name: PORT
          value: '7999'
        - name: NODE_ENV
          value: production
        - name: DB_NAME
          value: mldangelo
        - name: DB_HOST
          value: localhost
        - name: GA_ID
          value: 'UA-68649021-1'
        envFrom:
        - secretRef:
            name: website-env
        image: gcr.io/mldangelo-171318/github.com/mldangelo/personal-site@sha256:d4bca47cc9834c19548a12af97b428168eca05b836439a55b4708bdae4299f35
        name: website
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 7999
