apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: website-server
  name: website-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: website-server
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - --
        - npm deploy
        envFrom:
        - secretRef:
            name: website-env
        image: gcr.io/mldangelo-171318/github.com/mldangelo/personal-site@sha256:c0c12799b20510f8679ee78ef6b7ee3bbc7bc20b285dbd2de96669f0a63451e0
        imagePullPolicy: Always
        name: website
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 7999
